

trigger:
- main

pool:
  name: Default


stages:
- stage: EKS
  displayName: 'Environment Infra'
  jobs:
  - job: TerraformApply
    displayName: 'EKS and MongoDB'
    steps:
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: 'latest'
    
    - script: |
        echo "Initializing Terraform..."
        echo "no" | terraform init
      displayName: 'Terraform Init'
      

    - script: |
        echo "Executing Terraform Plan..."
        terraform plan -out=tfplan -var 'AWS_ACCESS_KEY_ID=$(aws-access-key)' -var 'AWS_SECRET_ACCESS_KEY=$(aws-secret-key)'
      displayName: 'Terraform Plan'
      continueOnError: true # This allows the pipeline to continue even if this step "fails"
      

    - script: |
       terraform apply "tfplan"
      
      continueOnError: true # This allows the pipeline to continue even if this step "fails"
      displayName: 'Terraform Apply'